name: DropZone
author: bootle
category: Utilities
tags: [upload, html5, chunk, drag & drop, flash]
docs: https://github.com/bootle/DropZone
demo: http://thebootle.com/foof/moo/DropZone/Demo/
#current: 0.9.1